### ISSUE TITLE
Checking Directory Structure

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica-tools/FMUComplianceChecker#14]
**Reported by mtiller on 17 Sep 2015 21:02 UTC**
  In working with JModelica, I identified an issue that probably appears in other tools and is a direct artifact of how Windows delimits directories.

  The issue I have found relates to page 40 of the FMI 1.0 specification.  I didn't check, but I suspect the same will be true for 2.0.  There, you will see that the specification very explicitly indicates that within an FMU, the structure should be:

binaries/
  win32/
    <modelIdentifier>.dll

  This indicates that the zip file (at least for Windows) should contain a directory named binaries which contains a directory named win32 which should contain the .dll files for the model.

  In JModelica, this is not the case although I suspect somehow unzip utilities are compensating in some way.  With JModelica, the file structure is this:

binaries\win32/
  <modelIdentifier>.dll

  The essential point here is the presence of the \ in the name.  The net effect here is that what you have created is a zip file with a directory named "binaries\win32" which contains the .dll files.  This is not simply an issue with my unzip tool, I've confirmed this more than one zip implementation.

  Given that most of these FMUs are run on Windows systems and tools in that environment probably have to be tolerant of such things, I can perfectly understand how this was not caught before.

  This is something that should be added to the FMI compliance checker

----

Migrated-From: https://trac.fmi-standard.org/ticket/348

**Comment by modelica-trac-importer** [comment]
**Comment by victor&#x2e;johnsson on 5 Apr 2016 09:41 UTC**
This has been fixed in Compliance Checker **2.0.3b1** which can be found here: https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/Compliance-Checker. Please make sure that you are satisfied that the issue has been resolved.

**Comment by filip-stenstrom** [comment]
Closing ticket since as victor.johnsson noted, some directory structure checking has been added. Also, I don't understand how a directory name could possible contain a backslash character on Windows.

**Comment by sjoelund** [comment]
> Also, I don't understand how a directory name could possible contain a backslash character on Windows.

Wasn't hard for me to create, but almost impossible to access the file afterwards :)

```
Z:\tmp> dir   

Directory of Z:\tmp

2020-06-17     09:38  <DIR>         .
2020-06-17     09:38  <DIR>         ..
2020-06-17     09:38            15  AB\D.mo
       1 file                        15 bytes
       2 directories    122,488,205,312 bytes free
```
