### ISSUE TITLE
Compliance checker: attribute initial forbidden for inputs

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica-tools/FMUComplianceChecker#24]
**Reported by cbertsch on 17 Jan 2017 17:11 UTC**
In the FMI 2.0 specification it is stated on p.47:
"Enumeration that defines how the variable is initialized. It is not allowed to provide a value for initial if causality = input or independent".
This is currently not checked by the compliance checker.
I attached an FMU containing this error.

----

Migrated-From: https://trac.fmi-standard.org/ticket/403

**Comment by ghorwin** [comment]
Seems there is a check implemented in current version 2.0.4, that forbids "causality=input", "variability=continuous" and "initial=exact" -> compliance checker requests and accepts "initial=approx"  in this case.

**Comment by filip-stenstrom** [comment]
Closing, since this has been fixed, as mentioned by @ghorwin.
