### ISSUE TITLE
Add pre-built Windows and Linux binaries to Release Assets

### ISSUE THREAD

**Issue by tbeu** [modelica-tools/FMUComplianceChecker#30]
Would be really nice if the binaries from https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/Compliance-Checker would also be available as assets at the [releases](https://github.com/modelica-tools/FMUComplianceChecker/releases) page.

**Comment by beutlich** [comment]
See step 7 of https://help.github.com/articles/creating-releases/

@chria As discussed again at the FMI Design meeting. Can you please care for it.

@t-sommer @chrbertsch @andreas-junghanns FYI

**Comment by beutlich** [comment]
@chria @victorjoh Any update on this?

**Comment by modelica-trac-importer** [comment]
Done. 15 mins of drag and drop.
