### ISSUE TITLE
CMakeLists.txt contains non-ascii characters (probably wrong quote chars)

### ISSUE THREAD

**Issue by ghorwin** [modelica-tools/FMUComplianceChecker#41]
In line 39 (and others) of CMakeLists.txt a comparison is made with the string ”unknown”, where the quote chars are not regular " quote chars, but others from a different code page. This may cause a build to fail or at least the check to fail. Unless intended, I suggest changing these to regular quotation characters.

**Comment by filip-stenstrom** [comment]
Closing since fixed in 8bc6a0f.
