### ISSUE TITLE
Unable to build FMI Compliance checker

### ISSUE THREAD

**Issue by rahulsetia** [modelica-tools/FMUComplianceChecker#44]
The steps mentioned build are incorrect. If we create a build dir and give cmake command in that directory as describd in build steps, it give an error that CMakeList.txt file does not exist. If we copy it to build dir, it give an error that CMakeList location is not same as where source was created. Moreover it also does not allow you to build in source dir.

**Comment by otronarp** [comment]
Sounds like you didn't provided the checker dir 

```
mkdir build; cd build
cmake -DFMUCHK_INSTALL_PREFIX=<dir name> <checker dir>
make install test
```

For that particular example it should be `..`, like this
```
mkdir build; cd build
cmake -DFMUCHK_INSTALL_PREFIX=install ..
make install test
```
This will install in `build/install`

**Comment by rahulsetia** [comment]
Thanks for the input, it helped.

**Comment by rahulsetia** [comment]
Can I specify location of FMIL(downloaded) rather than downloading it from svn ?

**Comment by hubertus65** [comment]
Solved through proper instructions
