### ISSUE TITLE
Incorrect  instance name initialized in cdata structure

### ISSUE THREAD

**Issue by rahulsetia** [modelica-tools/FMUComplianceChecker#46]
In line 37 in file fmi2_cs_sim.c, instanceNameToCompare initialized with incorrect value "Test FMI2.0 CS". The value is not overwritten anywhere again and thus I get a runtime error while using compliance checker. Should be initialized as in the attached file line 38 
and then the compliance checker works fine.

**Comment by filip-stenstrom** [comment]
I don't see anything wrong with the current implementation. If the FMU follows the standard, then the importer should be free to choose any name as specified in the documentation for `instanceName` in `fmi2Instantiate` in FMI 2.0.1:
> Argument instanceName is a unique identifier for the FMU instance. It is used to name the
instance, for example, in error or information messages generated by one of the fmi2XXX 
functions. It is not allowed to provide a null pointer and this string must be non-empty (in
other words, must have at least one character that is no white space) < ...non-normative-text>

Closing. Please re-open and provide error message if you disagree.
