### ISSUE TITLE
specify license explicitly

### ISSUE THREAD

**Issue by Bananeweizen** [modelica-tools/FMUComplianceChecker#53]
It is hard to understand the license for this project due to 2 reasons:
* the license.md is formatted wrongly, therefore the 3 bullet points of the license text are not seen as bullet points
* everyone coming along must identify the text of license.md by himself/herself. Please use the github repository settings to explicitly select "BSD 3 clause" (at least that is my guess for your license text). That way github will show that term immediately on the top right of the homepage, instead of only linking to the license.md file. See https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository for details.

**Comment by beutlich** [comment]
Duplicate of #36?

**Comment by Bananeweizen** [comment]
Yes.
