### ISSUE TITLE
failed to build the compliance checker 

### ISSUE THREAD

**Issue by ishengyeh** [modelica-tools/FMUComplianceChecker#65]
Hi, I got error message shown below when following BUILD.md to build the executable in Linux64, could you please help?  Thanks
--------------------------ERROR from installing the checker following BUILD.md 
cmake -DFMUCHK_INSTALL_PREFIX=../install /data1/isheng/fmu/FMUComplianceChecker-2.0.4
CMake Warning (dev) at CMakeLists.txt:151:
Syntax Warning in cmake code at column 85
-- FMIL version: Test
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:157 (add_dependencies):
Policy CMP0046 is not set: Error on non-existent dependency in <---- error message when cmake
add_dependencies
The dependency target
"/data1/isheng/fmu/FMUComplianceChecker-2.0.4/CMakeLists.txt" of target
"fmil" does not exist. <---- error message when cmake
CMake Warning (dev) at CMakeLists.txt:157 (add_dependencies):
Policy CMP0046 is not set: Error on non-existent dependency in
The dependency target
"/data1/isheng/fmu/FMUComplianceChecker-2.0.4/build/CMakeCache.txt" of
target "fmil" does not exist. <---- error message when cmake
-- Generating done
-- Build files have been written to: /data1/isheng/fmu/FMUComplianceChecker-2.0.4/build
FMUComplianceChecker-2.0.4/build% make install test
Scanning dependencies of target fmil
[ 5%] Creating directories for 'fmil'
[ 10%] Performing download step (SVN checkout) for 'fmil'
svn: E170013: Unable to connect to a repository at URL 'https://svn.jmodelica.org/FMILibrary/tags/2.0.3'
svn: E230001: Server SSL certificate verification failed: certificate issued for a different hostname
make[2]: *** [CMakeFiles/fmil.dir/build.make:109: FMIL/src/fmil-stamp/fmil-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/fmil.dir/all] Error 2

**Comment by iakovn** [comment]
FMI Library which is a dependency is no longer available at https://svn.jmodelica.org - it was moved to Github (https://github.com/modelon-community/fmi-library ). You need to either reconfigure in the build or use the master branch which is already updated.

**Comment by ishengyeh** [comment]
Thanks a lot, it works now.
